### ISSUE TITLE
Entering RegEx metacharacters causes a crash

### ISSUE THREAD

**Issue by Syl0s** [vackosar/search-based-launcher#10]
When you type RegEx metacharacters (+, *, (, ), {, }, ? etc.) into the search-field, then the launcher crashes.

Manually escaping these (i.e. typing "\\+", "\\*" etc.) fixes this. 

Therefore this can be fixed by programmatically escaping these characters, before they are fed into the RegEx interpreter.

**Comment by volnes** [comment]
+1
Yep problem is here.

**Comment by vackosar** [comment]
Yes, I came to same conclusion recently. Will fix that soon.

**Comment by vackosar** [comment]
@Syl0s, please retest and close.

**Comment by volnes** [comment]
special charaters like "\+", "\*" working. No crash

**Comment by Syl0s** [comment]
Finally got the update as well. Works now as intended.
