### ISSUE TITLE
Introduce wallpapers.

### ISSUE THREAD

**Issue by vackosar** [vackosar/search-based-launcher#14]
Redesign app to allow wallpapers.

**Comment by vackosar** [comment]
@volnes, introduced wallpapers.

**Comment by volnes** [comment]
how to disable this function?

**Comment by vackosar** [comment]
So far you can select black wallpaper in your android settings. But I will add this option into the app.

**Comment by volnes** [comment]
not needed to add this feature.
I think so)

**Comment by vackosar** [comment]
Not needed to add wallpapers or to add option to have black background
wallpaper?

**Comment by volnes** [comment]
>>add option to have black background
wow...
 This feature is needed!
I think u just add function to disable wallpapers ( but if u add option to have black background its would be very good)

**Comment by vackosar** [comment]
Will do that. By default old phones have ugly wallpapers i know. Btw you
can upload a black picture as a wallpaper now or some nicer on some phones.

**Comment by volnes** [comment]
what resolution needed?
i have black wallpaper with resolution 3264x2448 but i use a QuickPic to make lower 480x854.

Maybe try to use #FF000000 or 16777216 (0xff000000) ?

**Comment by vackosar** [comment]
Resolution depends on your phone.

**Comment by volnes** [comment]
![black-wallpaper](https://cloud.githubusercontent.com/assets/5400851/10334656/aa23a65e-6cfc-11e5-9f0a-59f2c745889d.jpg)

**Comment by volnes** [comment]
well upload? with high res? or what?
