### ISSUE TITLE
Introduce black, white background option into menu.

### ISSUE THREAD

**Issue by vackosar** [vackosar/search-based-launcher#17]

**Comment by vackosar** [comment]
@volnes, check it out!

**Comment by volnes** [comment]
There is bug when u choose wallpaper.
![screenshot_2015-10-11-10-55-33](https://cloud.githubusercontent.com/assets/5400851/10415899/1f425f2c-7007-11e5-9b2b-0fc96890493c.png)
![screenshot_2015-10-11-10-34-54](https://cloud.githubusercontent.com/assets/5400851/10415900/2861c3ea-7007-11e5-8525-0d8c4855d35b.png)

And font on white background need to change to black color.

![screenshot_2015-10-11-10-56-01](https://cloud.githubusercontent.com/assets/5400851/10415905/5c3634bc-7007-11e5-9119-bb4b89863dc9.png)

**Comment by vackosar** [comment]
@volnes, 
- wallpaper - yes. Will add hidden status bar.
- white - yes. Will not fix this yet.

**Comment by vackosar** [comment]
@volnes, can you retest?

**Comment by volnes** [comment]
Background wallpaper bug fixed, waiting for new color for white:-D
Thx for your work!

11 октября 2015 г. 15:25:33 Московское стандартное время, Vaclav Kosar <notifications@github.com> пишет:
>@volnes, can you retest?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/vackosar/search-based-launcher/issues/17#issuecomment-147187140

--

**Comment by vackosar** [comment]
@volnes Added black color for white background.
