### ISSUE TITLE
Move buttons into menu and app list.

### ISSUE THREAD

**Issue by vackosar** [vackosar/search-based-launcher#18]
@volnes, @Ferk, what do you think about this?

# Example App List
. Menu
Browser
Calendar
. Autostart Toggle

**Comment by volnes** [comment]
u disable all toggles from right?

**Comment by vackosar** [comment]
@volnes
All toggles would appear as applications in main application list. They would have some prefix by default so that you could find out what they are a part of the launcher. To toggle autostart button you would search and start application ". Autostart".

**Comment by vackosar** [comment]
@volnes, does that sound like a good idea to you? I think that would simplify the interface. I am not sure about the prefix however. How should it look like?

**Comment by volnes** [comment]
@vackosar hmm...nice idea! No more false taps!

Maybe prefix "T" (as "toggles")?

**Comment by vackosar** [comment]
@volnes  what about just prefixing with "Toggle ". 
- Users would find out because of the prefix and because it would be verb. 
- Also a popup dialog should inform them what action have been performed e.g. "Disabled autostart.".
- To search efficiently however you would have to use space character which matches anything: "t auto" would find "Toggle Autostart".

# Example
Toggle Autostart
Toggle Wifi
Toggle Bluetooth

**Comment by volnes** [comment]
:+1:

**Comment by vackosar** [comment]
Sounds like a plan!

**Comment by Ferk** [comment]
Sounds good.
But I guess this means that apps that start with T will also get in there.

Maybe add also a "Toggles" filter like the other filters in the options menu. That way you can get to the list of toggles with 2 taps (press menu then toggles).

**Comment by vackosar** [comment]
@Ferk 
yes the toggles also can be placed into menu for example.
Or add "." prefix to that. If you search for dot only toggles will be shown.

I suggest following 3 options:
- 1.: Just prefix ". Toggle ".
- 2.: Just prefix "Toggle ".
- 3.: Add toggles as extra options into Menu. Remove "Cam" toggle.

Personally I like the last best.

**Comment by volnes** [comment]
@vackosar 
>2.: Just prefix "Toggle ".
yes!
>3.: Add toggles as extra options into Menu. Remove "Cam" toggle.
hm...
>4.: Move toggle Autostart, Wiki into Menu.
Good idea!

**Comment by vackosar** [comment]
Partially done. Moved buttons to menu and removed Cam button.

**Comment by vackosar** [comment]
@volnes, @Ferk check out latest changes.

**Comment by volnes** [comment]
@vackosar new look of menu button is awesome!)))
Good job!

**Comment by vackosar** [comment]
@volnes, even more simplified now.
