### ISSUE TITLE
Optionally revert app list: Latest on the bottom.

### ISSUE THREAD

**Issue by vackosar** [vackosar/search-based-launcher#19]
One should scroll always from bottom to the top and the latest app should be on the bottom always just above the keyboard.

**Comment by vackosar** [comment]
@volnes, what do you think?

**Comment by volnes** [comment]
not bad)

**Comment by volnes** [comment]
Any news about that feature?

**Comment by vackosar** [comment]
Non. Didn't have time.

**Comment by vackosar** [comment]
@volnes I am afraid people may find it confusing. What do you think?

**Comment by husadd** [comment]
IMO just add an option for it.. better than forcing everyone to use it that way :)

**Comment by volnes** [comment]
@vackosar yes it's confusing a little

**Comment by vackosar** [comment]
Wont be implemented for now.
