### ISSUE TITLE
Redesign menu as an another list.

### ISSUE THREAD

**Issue by vackosar** [vackosar/search-based-launcher#22]

**Comment by vackosar** [comment]
- Create AppLister objects:
  - Implement load method.
- Optionaly implement save method.
  - Implement App can hold action.

**Comment by vackosar** [comment]
@volnes, check out new menu.

**Comment by volnes** [comment]
Good lookin! But no status info for "Autostart", like a "current" for hiding searchbar

**Comment by vackosar** [comment]
@volnes, can you retest? I cannot reproduce the problem on my devices.

**Comment by volnes** [comment]
well i mean no status of toggle "yes or "no" on "Autostart single result.

![screenshot_2015-10-19-07-20-05](https://cloud.githubusercontent.com/assets/5400851/10573761/58b7db02-7641-11e5-9026-56b0e243902e.png)

**Comment by vackosar** [comment]
Can you make a screenshot?

**Comment by volnes** [comment]
em...i make already here)))

i mean add a status for "Autostart single result" just like for  "hiding searchbar".
![screenshot_2015-10-19-07-20-18](https://cloud.githubusercontent.com/assets/5400851/10574004/d40ce9ae-7642-11e5-949f-12a51a636570.png)

**Comment by vackosar** [comment]
@volnes seems the cause is likely that the text description is too long.

**Comment by vackosar** [comment]
@volnes I shortened the items including the one above please retest.
