### ISSUE TITLE
Clean search box after match

### ISSUE THREAD

**Issue by jruere** [vackosar/search-based-launcher#26]
When searching for an app, if I keep typing after it matched, some characters are left when returning to the home screen. 

It would be awesome if the search box was cleared when not in foreground.

**Comment by volnes** [comment]
+1

**Comment by vackosar** [comment]
@jruere interesting as this never happened to me. I will have a look

**Comment by vackosar** [comment]
@jruere @volnes resolved please check and reopen if not fixed.

**Comment by jruere** [comment]
I cannot reproduce anymore. Thanks!
