### ISSUE TITLE
Hide keyboard option

### ISSUE THREAD

**Issue by volnes** [vackosar/search-based-launcher#29]
Could u add hide keyboard at start?
Until u tap on search bar?

**Comment by vackosar** [comment]
@volnes sounds like interesting option. Will have a look if it is possible.

**Comment by volnes** [comment]
@vackosar if u add this feature, it's awesome:-D
This feature makes Visual style of launcher more polished

**Comment by vackosar** [comment]
@volnes Done, please retest.

**Comment by volnes** [comment]
Well, it's work! Good job
