### ISSUE TITLE
Feature Request - Switch to running instance of apps

### ISSUE THREAD

**Issue by computerinfo21** [vackosar/search-based-launcher#31]
Would be really nice if instead of launching the app each time it would switch back to the running instance. This would make it ideal to switch between apps, not just launch them.
Currently it always goes to the main activity of an app, even if you previously left the app on a different activity.

**Comment by vackosar** [comment]
Interesting, will look into that.

**Comment by computerinfo21** [comment]
Usually it does switch back correctly, but there are instances when it does not.

This may be the fault of individual apps not saving their state correctly, but it is frustrating to have to even think about when it is safe to use Search Based Launcher to switch between apps and when it is not.

An easy test is Simpletask (https://f-droid.org/repository/browse/?fdid=nl.mpcjanssen.simpletask). While adding a task, if I hit the home button to go back to Search Based Launcher, then using Search Based Launcher select Simpletask again, it loses whatever I was typing on the Add Task screen and goes to the main screen. However, if I switch back to Simpletask using an application switcher, such as the built in Android one (hold down on Home button typically brings it up), it correctly switches back to the Add Task screen so I can continue typing without losing what I have already typed.
I will often be copying text from one app and pasting it in another app when I have this problem.

**Comment by vackosar** [comment]
Please retry as soon as I release. I am attempting to fix this, but was not able to simulate the issue as was always getting to the Simpletask Main Screen regardless launcher.

**Comment by computerinfo21** [comment]
Awesome! Thanks for working on it!
Just updated to version 58 and tested again, same result unfortunately.

I dug through some code and read some about it and it looks like re-ordering the task to the front might be the only fix for apps that do not behave properly.
Activity Manager has a "moveTaskToFront()" that should work. It would require getting a list of running tasks and checking them to see if one of them is the requested app and moving it to the front instead of the usual startActivity(intent), otherwise launching like usual.
Shouldn't be much of a performance hit, but might be better as an optional setting those of us who have the problem can just turn on since people love this being so fast?

**Comment by vackosar** [comment]
Apparently getting list of runnign tasks won't be that easy see https://developer.android.com/reference/android/app/ActivityManager.html#getRunningTasks(int)
However I may have used wrong flag previously. Testing...

**Comment by vackosar** [comment]
@computerinfo21 can you retest on v59?

**Comment by vackosar** [comment]
Please reopen if this is still issue on v59.

**Comment by computerinfo21** [comment]
Nope, still not fixed when I test with Simpletask. I wrote some code and submitted a pull request to KISS (another search based launcher, see https://github.com/Neamar/KISS/pull/489/commits/4b77c3051cccca3c8c9405caf9565804312b17af).
When I was testing trying to get it to work for that pull request, getting the running tasks and re-ordering to the one to the front was the only thing that worked to resolve it. I did try each of the flags that sounded promising.
They ended up not merging that code because it requires asking for another permission and since most apps do not have the problem they decided it would be best for their users to not have to accept another permission. So I will leave it up to you on whether this should be re-opened and fixed or not knowing all of that.
Either way, thank you for your efforts on it! I appreciate it and really love this launcher regardless!

**Comment by vackosar** [comment]
I am sorry that it did not fix the problem. I cannot afford to ask users for the permission listed in https://github.com/vackosar/search-based-launcher/issues/31#issuecomment-269542731
But if you really want to have some special code, you can always rebuild the project with that personal change you would like to have. It is however more laborious.

**Comment by computerinfo21** [comment]
Understandable. I probably will build a custom version for myself & keep it updated with changes you make since it is an issue I deal with. Keep making this launchear better! It is fantastic!
