### ISSUE TITLE
[bug]After reboot some apps may not showing in app list

### ISSUE THREAD

**Issue by volnes** [vackosar/search-based-launcher#32]
This happens every time when my phone rebooting, after restart launcher twice, all fine

**Comment by vackosar** [comment]
Can you be specific on which apps do this? I am resolving similar issue just now.

**Comment by vackosar** [comment]
Can you retry on latest version?

**Comment by vackosar** [comment]
@volnes, is this still a problem?

**Comment by vackosar** [comment]
Please reopen if this is still issue on v59.
