### ISSUE TITLE
[FEATURE REQUEST] - Beautify UI

### ISSUE THREAD

**Issue by J316** [vackosar/search-based-launcher#34]
Give it a slightly nicer UI by separating search field with a line, making possible to align text to left or right too, adding apps and toggles icons

**Comment by volnes** [comment]
Nah...icons not needed, simple text based interface is feature of this launcher

**Comment by vackosar** [comment]
@J316, 
- Text aligning is already possible. See menu.
- Will consider adding icons as optional.
