### ISSUE TITLE
sometimes reopens app when pressing home

### ISSUE THREAD

**Issue by jruere** [vackosar/search-based-launcher#36]
On some occasions, after opening an app, using it and the pressing the home button, the app reopens.

This can be reproduced reliably this way: 
1. Type the apps name
2. The app opens
3. Press back
4. The app closes and reopens immediately

If the app name in the list is pressed, this doesn't happen.

**Comment by vackosar** [comment]
Just reproduced it. Lookin for fix.

**Comment by vackosar** [comment]
Please retry.

**Comment by jruere** [comment]
Works perfectly. Thanks!
