### ISSUE TITLE
Feature request. Allow manual sorting app list

### ISSUE THREAD

**Issue by rocker1966** [vackosar/search-based-launcher#38]
It would be convenient to sort apps manually. Now recently launched app goes to top. If one has not so many apps it may be good to have fixed list

**Comment by vackosar** [comment]
Not sure about sorting manually, but what about rather allowing to turn off "recent apps on top" functionality?

**Comment by vackosar** [comment]
Actually that is suggested in #40. I will consider only that one for now.
