### ISSUE TITLE
Two apps launch

### ISSUE THREAD

**Issue by snan** [vackosar/search-based-launcher#39]
I've figured out what makes it so that sometimes two apps launch: it's because if I type more characters after the first app has launched, Search Based Launcher is still listening.

For example, I have two apps "Notes" and "Text Fiction". I started writing "note" because I wanted to launch "Notes", and "no" was enough to launch "Notes" unambiguously, and "te" was enough to launch "Text Fiction" unambiguously, so both launched. This isn't good -- I want type quickly and end up in the right app, rather to deliberately go one letter at a time and select from the list.

The list filtered on "note" disappeared as soon as I wrote the "no", and started over with a list filtered on "te". Ideally, it's good to keep the feature that "Notes" is starting as soon as the "o" comes down, and please do keep that, but while it's waiting, just keep the same filtered view.

The issue is that `AppExecutor.act` starts a new search so quickly It should hold off on that `searchText.clearText()` call until the user come back properly from the newly launched activity.

I don't really know how to do that...

Btw, big thanks for this wonderful launcher ♥

**Comment by vackosar** [comment]
Sorry noticed just now thanks to @cyBerta . Strangely I haven't received any mail regarding this.

**Comment by vackosar** [comment]
@snan on which android version this issue occurs?

**Comment by vackosar** [comment]
@cyBerta, this seems to be rather problem with OnResumeEvent being executed too early or unexpectedly as text shouldn't be cleared until application is resumed. I was forced to use OnResumeEvent this instead of the OnStartEvent as there were complaints text wouldn't get cleared at all in the past.

**Comment by snan** [comment]
I'm on 4.2.2 (yeah, I know).
But not sure it's `OnResumeEvent` that's the culprit. The behavior is that I'm in search-based-launcher continuously, typing in the word (the list clearing after the two words), then after that the two apps start.
I.e. it doesn't leave search-based-launcher so it can't resume.

`clearText` is called on `OnResumeEvent`, yes, but that's not the only place, it's called in `AppExecutor.act` too.

`AppExecutor.act` is called indirectly from `refreshView` which is called all over the place. @cyBerta's commit prevents some of those calls, thus preventing some of those extra `clearText` calls. I.e. those not stemming from `OnResumeEvent`.

**Comment by vackosar** [comment]
You are right it is in the `AppExecutor.act` as well. It was added as part of #36.

**Comment by vackosar** [comment]
I think rather moving the `clearText` call into `onPauseEvent` block would be better. But I admit that some kind of blocking boolean may be still needed.

### Refs:
- https://developer.android.com/guide/components/activities/activity-lifecycle.html
- https://github.com/roboguice/roboguice/wiki/Using-Events-in-your-RoboGuice-application

**Comment by vackosar** [comment]
I cannot reproduce the issue described, so you will have to test this on your device. I will release soon including the onPauseEvent clearing to satisfy both #36 and this #39.

**Comment by vackosar** [comment]
I've added a commit that may fix or improve the issue, will release it soon.

**Comment by vackosar** [comment]
I can reproduce this issue now on one of my devices. Will be able to fix properly.

**Comment by vackosar** [comment]
@snan, can you retest with version 59?

**Comment by vackosar** [comment]
Please reopen if this is still an issue on v59.

**Comment by snan** [comment]
Yes, this fixes the issue. Thank you so much!
