### ISSUE TITLE
Problem with "autorun" button

### ISSUE THREAD

**Issue by volnes** [vackosar/search-based-launcher#6]
When launcher killed by oom killer and was restarted, the autostart button is enabled by default, but i turn it off.
It's annoying always turn off "autorun" button when launcher restarted.

**Comment by vackosar** [comment]
Released.

**Comment by volnes** [comment]
Problem still here...autorun button change status from time to time...

**Comment by vackosar** [comment]
Couldnt reproduce on Android 5.1. Please share your Android version. Will debug on your version.

**Comment by volnes** [comment]
version 4.0.4
This happen when launcher killed by oom.
When laucher was restarted Autostart button state is on (enabled).
Maybe make Autostart button is off by default?

**Comment by vackosar** [comment]
Probably found the issue. Please retest.

**Comment by volnes** [comment]
now state of button working good!

**Comment by volnes** [comment]
And again state of "Autorun" changing to "yes" when launcher is restarted

@vackosar
