### ISSUE TITLE
Feature request: most used apps list or sorting by used apps

### ISSUE THREAD

**Issue by volnes** [vackosar/search-based-launcher#7]

**Comment by vackosar** [comment]
Can you retest? Recently started apps should be on the top.

**Comment by volnes** [comment]
Well all work now fine! awesome work!

**Comment by vackosar** [comment]
In long term, it would still be better to have all the apps sorted right? I can create a mile stone and can work out some transition steps.

**Comment by volnes** [comment]
sorted by...using? i think it's good idea
