### ISSUE TITLE
Not always showed "R:" prefix when lauched any app.

### ISSUE THREAD

**Issue by volnes** [vackosar/search-based-launcher#8]
When i start any app from list of all apps and back to launcher, the "R:" prefix not showed on that app.
But if i press "Menu" button and go back to all applications list  "R:" prefix showed fine!

**Comment by vackosar** [comment]
Can you retest on the newest version? I changed the code architecture little bit.

**Comment by volnes** [comment]
now this problem solved, but issue #6 is still here.
