### ISSUE TITLE
Search based launcher v3 (from f-droid) doesn't see the Google Drive app

### ISSUE THREAD

**Issue by bet** [vackosar/search-based-launcher#9]
The older search based launcher on f-droid didn't have this problem. I use a Nexus 5 running stock 5.1.1 LMY48M. I type 'dr' and it auto launches a separate app, Drive Autosync. Can't get it to start Drive.

**Comment by bet** [comment]
I tried toggling off autostart, and then I could type in drive and see it, but then it launched docs, which in turn had a sidebar option to go to Drive, so perhaps Search Based Launcher isn't seeing all the distinct apps.

**Comment by vackosar** [comment]
Strange. Have tried searching for it in list of all activities?

**Comment by bet** [comment]
"Drive" sometimes shows up as an app, but immediately launches "Docs", it flashes the name change as soon as I tap Drive, and Docs shows up in the history. Since Docs has an option in the sidebar to get to Drive, it seems like Search Based Launcher isn't seeing both apps and is preferring Docs.

**Comment by bet** [comment]
With the update to 45 (from 39) that I just got, this issue seems to be fixed. I'll try to mark the issue closed. Thanks!
